;; Handwritten simulation, f64 throughout. No imports or host math calls.
;; ABI: state f64[7] @ 0; config f64[10] @ 64; impact times f64[50] @ 512;
;; previous state @ 224; batch duration/result @ 288; simulation time @ 304;
;; impact records {peg,strength,velocity,time}: f64[4] @ 1024 (512 records);
;; seed staging u32[8192] @ 32768. One fixed page per instance; no allocator.
(module
  (memory (export "memory") 1 1)
  (global $fixedDt f64 (f64.const 0.004166666666666667))
  (global $captureEvents (mut i32) (i32.const 1))
  (global $decay (mut f64) (f64.const 1))
  (global $tau f64 (f64.const 6.283185307179586))
  (global $pi f64 (f64.const 3.141592653589793))
  (global $halfPi f64 (f64.const 1.5707963267948966))
  (global $a (mut f64) (f64.const 0))
  (global $w (mut f64) (f64.const 0))
  (global $p (mut f64) (f64.const 0))
  (global $v (mut f64) (f64.const 0))
  (global $stable (mut f64) (f64.const 0))
  (global $strength (mut f64) (f64.const 0))
  (global $count (mut i32) (i32.const 8))
  (global $lastPeg (mut i32) (i32.const -1))
  (global $audibleContacts (mut i64) (i64.const 0))
  (global $contactPeg (mut i32) (i32.const -1))
  (global $contactDirection (mut f64) (f64.const 1))
  (global $contactTorque (mut f64) (f64.const 0))
  (global $lastDirection (mut f64) (f64.const 1))
  (global $lastImpactTime (mut f64) (f64.const -1))
  (global $time (mut f64) (f64.const 0))
  (global $launchTorque (mut f64) (f64.const 0))
  (global $brakeScale (mut f64) (f64.const 1))
  (global $launchRemaining (mut f64) (f64.const 0))
  (global $restitutionScale (mut f64) (f64.const 1))
  (global $dragScale (mut f64) (f64.const 1))
  (global $events (mut i32) (i32.const 0))
  (global $rng (mut i32) (i32.const 1))
  ;; Config order is shared with WasmCore.ts.
  (global $inertia (mut f64) (f64.const 0))
  (global $linear (mut f64) (f64.const 0))
  (global $brake (mut f64) (f64.const 0))
  (global $quadratic (mut f64) (f64.const 0))
  (global $friction (mut f64) (f64.const 0))
  (global $spring (mut f64) (f64.const 0))
  (global $damping (mut f64) (f64.const 0))
  (global $pointerInertia (mut f64) (f64.const 0))
  (global $restitution (mut f64) (f64.const 0))
  (global $coupling (mut f64) (f64.const 0))

  (func $clamp (param $x f64) (param $lo f64) (param $hi f64) (result f64)
    (f64.max (local.get $lo) (f64.min (local.get $hi) (local.get $x))))
  (func $sign (param $x f64) (result f64)
    (if (result f64) (f64.eq (local.get $x) (f64.const 0))
      (then (local.get $x)) (else (f64.copysign (f64.const 1) (local.get $x)))))
  ;; JS Math.round uses ties toward +infinity, unlike f64.nearest.
  (func $round (export "math_round") (param $x f64) (result f64) (local $floor f64)
    (local.set $floor (f64.floor (local.get $x)))
    (if (result f64) (f64.lt (f64.sub (local.get $x) (local.get $floor)) (f64.const 0.5))
      (then (local.get $floor))
      (else (f64.copysign (f64.abs (f64.add (local.get $floor) (f64.const 1))) (local.get $x)))))
  ;; Simulation angles stay small: wrapped each integration step. Truncation
  ;; supplies remainder semantics for negative rotations, then wraps to [0,tau).
  (func $wrap (export "math_wrap") (param $x f64) (result f64) (local $original f64)
    (local.set $original (local.get $x))
    (local.set $x (f64.sub (local.get $x)
      (f64.mul (f64.trunc (f64.div (local.get $x) (global.get $tau))) (global.get $tau))))
    (if (f64.eq (local.get $x) (f64.const 0))
      (then (return (f64.copysign (f64.const 0) (local.get $original)))))
    (if (result f64) (f64.lt (local.get $x) (f64.const 0))
      (then (f64.add (local.get $x) (global.get $tau))) (else (local.get $x))))
  (func $signed (param $x f64) (result f64)
    (local.set $x (f64.sub (call $wrap (f64.add (local.get $x) (global.get $pi))) (global.get $pi)))
    (if (result f64) (f64.eq (local.get $x) (f64.neg (global.get $pi)))
      (then (global.get $pi)) (else (local.get $x))))
  ;; Sine: reduce to [-pi/2,pi/2], then a degree-21 Taylor polynomial
  ;; evaluated in Horner form with constant coefficients, no loops/divisions. The omitted term is < 1.3e-18 on this interval.
  ;; This is a bounded simulation routine, not arbitrary-magnitude libm.
  (func $sin (export "math_sin") (param $x f64) (result f64)
    (local $polynomial f64) (local $square f64)
    (local.set $x (call $signed (local.get $x)))
    (if (f64.gt (local.get $x) (global.get $halfPi))
      (then (local.set $x (f64.sub (global.get $pi) (local.get $x)))))
    (if (f64.lt (local.get $x) (f64.neg (global.get $halfPi)))
      (then (local.set $x (f64.sub (f64.neg (global.get $pi)) (local.get $x)))))
    (local.set $square (f64.mul (local.get $x) (local.get $x)))
    (local.set $polynomial (f64.const 1.9572941063391263e-20))
    (local.set $polynomial (f64.add (f64.const -8.2206352466243295e-18) (f64.mul (local.get $square) (local.get $polynomial))))
    (local.set $polynomial (f64.add (f64.const 2.8114572543455206e-15) (f64.mul (local.get $square) (local.get $polynomial))))
    (local.set $polynomial (f64.add (f64.const -7.6471637318198164e-13) (f64.mul (local.get $square) (local.get $polynomial))))
    (local.set $polynomial (f64.add (f64.const 1.6059043836821613e-10) (f64.mul (local.get $square) (local.get $polynomial))))
    (local.set $polynomial (f64.add (f64.const -2.505210838544172e-08) (f64.mul (local.get $square) (local.get $polynomial))))
    (local.set $polynomial (f64.add (f64.const 2.7557319223985893e-06) (f64.mul (local.get $square) (local.get $polynomial))))
    (local.set $polynomial (f64.add (f64.const -0.00019841269841269841) (f64.mul (local.get $square) (local.get $polynomial))))
    (local.set $polynomial (f64.add (f64.const 0.0083333333333333332) (f64.mul (local.get $square) (local.get $polynomial))))
    (local.set $polynomial (f64.add (f64.const -0.16666666666666666) (f64.mul (local.get $square) (local.get $polynomial))))
    (f64.add (local.get $x) (f64.mul (f64.mul (local.get $x) (local.get $square)) (local.get $polynomial))))
  (func $cos (export "math_cos") (param $x f64) (result f64)
    (call $sin (f64.add (local.get $x) (global.get $halfPi))))
  ;; exp(-9*substepDt): range-reduced exponential, degree-16 series followed
  ;; by exact power-of-two scaling. Horner evaluation uses constant coefficients. Supports the full finite normal range;
  ;; underflow below the smallest normal is deliberately flushed to zero.
  (func $exp (export "math_exp") (param $x f64) (result f64)
    (local $k i32) (local $r f64) (local $sum f64)
    (if (f64.ne (local.get $x) (local.get $x)) (then (return (local.get $x))))
    (if (f64.gt (local.get $x) (f64.const 709.782712893384)) (then (return (f64.const inf))))
    (if (f64.lt (local.get $x) (f64.const -708.3964185322641)) (then (return (f64.const 0))))
    (local.set $k (i32.trunc_f64_s (f64.nearest (f64.mul (local.get $x) (f64.const 1.4426950408889634)))))
    ;; Split ln(2) keeps the reduction accurate when k is large.
    (local.set $r (f64.sub
      (f64.sub (local.get $x) (f64.mul (f64.convert_i32_s (local.get $k)) (f64.const 0.6931471803691238)))
      (f64.mul (f64.convert_i32_s (local.get $k)) (f64.const 1.9082149292705877e-10))))
    (local.set $sum (f64.const 4.7794773323873853e-14))
    (local.set $sum (f64.add (f64.const 7.6471637318198164e-13) (f64.mul (local.get $r) (local.get $sum))))
    (local.set $sum (f64.add (f64.const 1.1470745597729725e-11) (f64.mul (local.get $r) (local.get $sum))))
    (local.set $sum (f64.add (f64.const 1.6059043836821613e-10) (f64.mul (local.get $r) (local.get $sum))))
    (local.set $sum (f64.add (f64.const 2.08767569878681e-09) (f64.mul (local.get $r) (local.get $sum))))
    (local.set $sum (f64.add (f64.const 2.505210838544172e-08) (f64.mul (local.get $r) (local.get $sum))))
    (local.set $sum (f64.add (f64.const 2.7557319223985888e-07) (f64.mul (local.get $r) (local.get $sum))))
    (local.set $sum (f64.add (f64.const 2.7557319223985893e-06) (f64.mul (local.get $r) (local.get $sum))))
    (local.set $sum (f64.add (f64.const 2.4801587301587302e-05) (f64.mul (local.get $r) (local.get $sum))))
    (local.set $sum (f64.add (f64.const 0.00019841269841269841) (f64.mul (local.get $r) (local.get $sum))))
    (local.set $sum (f64.add (f64.const 0.0013888888888888889) (f64.mul (local.get $r) (local.get $sum))))
    (local.set $sum (f64.add (f64.const 0.0083333333333333332) (f64.mul (local.get $r) (local.get $sum))))
    (local.set $sum (f64.add (f64.const 0.041666666666666664) (f64.mul (local.get $r) (local.get $sum))))
    (local.set $sum (f64.add (f64.const 0.16666666666666666) (f64.mul (local.get $r) (local.get $sum))))
    (local.set $sum (f64.add (f64.const 0.5) (f64.mul (local.get $r) (local.get $sum))))
    (local.set $sum (f64.add (f64.const 1) (f64.mul (local.get $r) (local.get $sum))))
    (local.set $sum (f64.add (f64.const 1) (f64.mul (local.get $r) (local.get $sum))))
    (if (i32.eq (local.get $k) (i32.const 1024))
      (then (return (f64.mul (f64.mul (local.get $sum) (f64.const 2)) (f64.const 8.98846567431158e307)))))
    (f64.mul (local.get $sum)
      (f64.reinterpret_i64 (i64.shl (i64.extend_i32_s (i32.add (local.get $k) (i32.const 1023))) (i64.const 52)))))
  (func $hypot (export "math_hypot") (param $x f64) (param $y f64) (result f64)
    (local $hi f64) (local $lo f64)
    (local.set $hi (f64.max (f64.abs (local.get $x)) (f64.abs (local.get $y))))
    (local.set $lo (f64.min (f64.abs (local.get $x)) (f64.abs (local.get $y))))
    (if (f64.eq (local.get $hi) (f64.const 0)) (then (return (f64.const 0))))
    (if (f64.eq (local.get $hi) (f64.const inf)) (then (return (f64.const inf))))
    (local.set $lo (f64.div (local.get $lo) (local.get $hi)))
    (f64.mul (local.get $hi) (f64.sqrt (f64.add (f64.const 1) (f64.mul (local.get $lo) (local.get $lo))))))

  ;; FNV-1a seed words followed by xorshift32, all integer operations in Wasm.
  (func (export "hash_seed") (param $hash i32) (param $length i32) (result i32) (local $i i32)
    (block $done (loop $words
      (br_if $done (i32.ge_u (local.get $i) (local.get $length)))
      (local.set $hash (i32.mul (i32.xor (local.get $hash)
        (i32.load (i32.add (i32.const 32768) (i32.mul (local.get $i) (i32.const 4))))) (i32.const 0x01000193)))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $words)))
    (local.get $hash))
  (func (export "finish_seed") (param $hash i32) (result i32)
    (select (local.get $hash) (i32.const 0x9e3779b9) (local.get $hash)))
  (func $next (result f64)
    (global.set $rng (i32.xor (global.get $rng) (i32.shl (global.get $rng) (i32.const 13))))
    (global.set $rng (i32.xor (global.get $rng) (i32.shr_u (global.get $rng) (i32.const 17))))
    (global.set $rng (i32.xor (global.get $rng) (i32.shl (global.get $rng) (i32.const 5))))
    (f64.div (f64.convert_i32_u (global.get $rng)) (f64.const 4294967296)))
  (func $range (param $min f64) (param $max f64) (result f64)
    (f64.add (local.get $min) (f64.mul (f64.sub (local.get $max) (local.get $min)) (call $next))))
  (func (export "rng_sample") (param $state i32) (param $min f64) (param $max f64) (result f64)
    (global.set $rng (local.get $state)) (call $range (local.get $min) (local.get $max)))
  (func (export "rng_state") (result i32) (global.get $rng))
  (func $launchSpeed (export "launch_speed") (param $charge f64) (param $r1 f64) (param $r2 f64) (result f64)
    (local $power f64) (local $charged f64) (local $preload f64)
    (local.set $charge (call $clamp (local.get $charge) (f64.const 0) (f64.const 1)))
    ;; The only power used by the model is x^1.5 on [0,1].
    (local.set $power (f64.mul (local.get $charge) (f64.sqrt (local.get $charge))))
    (local.set $charged (f64.add (f64.const 4.2) (f64.mul (f64.const 20) (local.get $power))))
    (local.set $preload (f64.mul (f64.mul (f64.const 200) (f64.add (f64.const 1) (local.get $power)))
      (f64.add (local.get $r1) (local.get $r2))))
    (f64.sqrt (f64.add (f64.mul (local.get $charged) (local.get $charged)) (local.get $preload))))
  (func $smooth (param $x f64) (result f64)
    (f64.mul (f64.mul (local.get $x) (local.get $x)) (f64.sub (f64.const 3) (f64.mul (f64.const 2) (local.get $x)))))
  (func $brakeTorque (export "brake_torque") (param $w f64) (param $strength f64) (result f64)
    (f64.mul (f64.mul (f64.neg (local.get $strength))
      (call $smooth (call $clamp (f64.div (f64.sub (f64.abs (local.get $w)) (f64.const 0.12)) (f64.const 0.38))
        (f64.const 0) (f64.const 1)))) (local.get $w)))
  (func $brakeRelease (export "brake_release") (param $charge f64) (result f64)
    (f64.sub (f64.const 1) (f64.mul (f64.const 0.8)
      (call $smooth (call $clamp (f64.div (f64.sub (local.get $charge) (f64.const 0.55)) (f64.const 0.45))
        (f64.const 0) (f64.const 1))))))

  (func $read
    (global.set $a (f64.load (i32.const 0))) (global.set $w (f64.load (i32.const 8)))
    (global.set $p (f64.load (i32.const 16))) (global.set $v (f64.load (i32.const 24)))
    (global.set $stable (f64.load (i32.const 32))) (global.set $strength (f64.load (i32.const 40)))
  )
  (func (export "configure")
    (global.set $inertia (f64.load (i32.const 64))) (global.set $linear (f64.load (i32.const 72)))
    (global.set $brake (f64.load (i32.const 80))) (global.set $quadratic (f64.load (i32.const 88)))
    (global.set $friction (f64.load (i32.const 96))) (global.set $spring (f64.load (i32.const 104)))
    (global.set $damping (f64.load (i32.const 112))) (global.set $pointerInertia (f64.load (i32.const 120)))
    (global.set $restitution (f64.load (i32.const 128))) (global.set $coupling (f64.load (i32.const 136))))
  (func $writeState (param $address i32)
    (f64.store offset=0 (local.get $address) (global.get $a)) (f64.store offset=8 (local.get $address) (global.get $w))
    (f64.store offset=16 (local.get $address) (global.get $p)) (f64.store offset=24 (local.get $address) (global.get $v))
    (f64.store offset=32 (local.get $address) (global.get $stable)) (f64.store offset=40 (local.get $address) (global.get $strength))
    (f64.store offset=48 (local.get $address) (f64.convert_i32_s (global.get $lastPeg))))
  (func $publish
    (call $writeState (i32.const 0))
    (f64.store (i32.const 304) (global.get $time)))
  (func $clearImpacts (local $i i32)
    (global.set $audibleContacts (i64.const 0))
    (loop $clear
      (f64.store (i32.add (i32.const 512) (i32.mul (local.get $i) (i32.const 8))) (f64.const -inf))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br_if $clear (i32.lt_u (local.get $i) (i32.const 50)))))
  (func $setCount (export "set_count") (param $count f64)
    (global.set $count (i32.trunc_f64_s (call $clamp (call $round (local.get $count)) (f64.const 2) (f64.const 50))))
    (global.set $lastPeg (i32.const -1)) (global.set $contactPeg (i32.const -1))
    (call $clearImpacts)
    (f64.store (i32.const 48) (f64.const -1)))
  (func (export "get_count") (result i32) (global.get $count))
  (func (export "init") (param $count f64)
    (call $setCount (local.get $count))
    (global.set $a (call $wrap (f64.sub (global.get $halfPi) (f64.div (global.get $pi) (f64.convert_i32_s (global.get $count))))))
    (call $publish) (call $writeState (i32.const 224)))
  (func (export "launch") (param $charge f64) (param $seed i32) (local $target f64)
    (call $read) (global.set $rng (local.get $seed))
    (global.set $w (f64.const 0)) (global.set $lastPeg (i32.const -1)) (global.set $contactPeg (i32.const -1))
    (global.set $contactDirection (f64.const 1)) (global.set $lastDirection (f64.const 1))
    (global.set $contactTorque (f64.const 0)) (global.set $lastImpactTime (f64.const -1))
    (call $clearImpacts) (global.set $time (f64.const 0)) (global.set $strength (f64.const 0))
    (global.set $events (i32.const 0))
    (global.set $brakeScale (call $brakeRelease (local.get $charge)))
    (local.set $target (call $launchSpeed (local.get $charge) (call $next) (call $next)))
    (global.set $launchRemaining (call $range (f64.const 0.065) (f64.const 0.095)))
    (global.set $launchTorque (f64.div (f64.mul (local.get $target) (global.get $inertia)) (global.get $launchRemaining)))
    (global.set $p (call $range (f64.const -0.012) (f64.const 0.012)))
    (global.set $v (call $range (f64.const -0.08) (f64.const 0.08)))
    (global.set $dragScale (call $range (f64.const 0.985) (f64.const 1.015)))
    (global.set $restitutionScale (call $range (f64.const 0.96) (f64.const 1.04)))
    (global.set $stable (f64.const 0)) (call $publish) (call $writeState (i32.const 224)))
  (func (export "is_settled") (result i32) (f64.ge (f64.load (i32.const 32)) (f64.const 0.35)))
  (func (export "event_count") (result i32) (global.get $events))
  (func $pegIndex (param $logical f64) (result i32) (local $index i32)
    (local.set $index (i32.rem_s (i32.trunc_f64_s (local.get $logical)) (global.get $count)))
    (i32.rem_s (i32.add (local.get $index) (global.get $count)) (global.get $count)))
  (func $notify (param $peg i32) (param $strength f64) (local $address i32)
    (local.set $address (i32.add (i32.const 512) (i32.mul (local.get $peg) (i32.const 8))))
    (if (f64.lt (f64.sub (global.get $time) (f64.load (local.get $address))) (f64.const 0.025)) (then (return)))
    (f64.store (local.get $address) (global.get $time))
    ;; Diagnostics retain deduplication state but do not accumulate audio.
    (if (i32.eqz (global.get $captureEvents)) (then (return)))
    ;; A 30-tick frame spans 0.125s. The 25ms per-pin cooldown bounds it to
    ;; at most 300 events (50 pins * 6); single ticks have at most 256 attempts.
    (if (i32.ge_u (global.get $events) (i32.const 512)) (then unreachable))
    (local.set $address (i32.add (i32.const 1024) (i32.mul (global.get $events) (i32.const 32))))
    (f64.store (local.get $address) (f64.convert_i32_s (local.get $peg)))
    (f64.store offset=8 (local.get $address) (local.get $strength))
    (f64.store offset=16 (local.get $address) (global.get $w))
    (f64.store offset=24 (local.get $address) (global.get $time))
    (global.set $events (i32.add (global.get $events) (i32.const 1))))
  (func $emitContact (param $peg i32) (local $strength f64)
    (global.set $lastPeg (local.get $peg)) (global.set $lastImpactTime (global.get $time))
    (local.set $strength (call $clamp (f64.div (f64.abs (global.get $w)) (f64.const 17)) (f64.const 0.06) (f64.const 1)))
    (global.set $strength (local.get $strength)))
  (func $collide (param $peg i32) (local $relative f64) (local $strength f64) (local $direction f64) (local $impulse f64)
    (if (i32.eq (local.get $peg) (global.get $contactPeg)) (then (return)))
    (if (i32.and (i32.eq (local.get $peg) (global.get $lastPeg))
      (f64.lt (f64.sub (global.get $time) (global.get $lastImpactTime)) (f64.const 0.025))) (then (return)))
    (global.set $lastPeg (local.get $peg)) (global.set $lastImpactTime (global.get $time))
    (local.set $relative (f64.sub (global.get $w) (f64.mul (global.get $v) (f64.const 0.18))))
    (local.set $strength (call $clamp (f64.div (f64.abs (local.get $relative)) (f64.const 17)) (f64.const 0.06) (f64.const 1)))
    (local.set $direction (call $sign (local.get $relative)))
    (if (f64.eq (local.get $direction) (f64.const 0)) (then (local.set $direction (f64.const 1))))
    (local.set $impulse (f64.mul (f64.mul
      (f64.mul (f64.neg (local.get $direction)) (f64.add (f64.const 2.5) (f64.mul (f64.const 10) (local.get $strength))))
      (global.get $restitution)) (global.get $restitutionScale)))
    (global.set $v (f64.add (global.get $v) (local.get $impulse)))
    (global.set $w (f64.sub (global.get $w) (f64.mul (local.get $direction)
      (f64.add (f64.const 0.012) (f64.mul (f64.mul (local.get $strength) (global.get $coupling)) (f64.const 0.55))))))
    (global.set $strength (local.get $strength)))
  (func $crossings (param $previous f64) (param $current f64)
    (local $step f64) (local $delta f64) (local $direction f64) (local $line f64)
    (local $from f64) (local $to f64) (local $crossings i32) (local $n i32) (local $boundary f64)
    (local.set $step (f64.div (global.get $tau) (f64.convert_i32_s (global.get $count))))
    (local.set $delta (call $signed (f64.sub (local.get $current) (local.get $previous))))
    (if (f64.lt (f64.abs (local.get $delta)) (f64.const 1e-9)) (then (return)))
    (local.set $direction (call $sign (local.get $delta)))
    (local.set $line (f64.add (global.get $halfPi) (f64.mul (local.get $direction)
      (f64.min (f64.const 0.06) (f64.mul (local.get $step) (f64.const 0.28))))))
    (local.set $from (f64.floor (f64.div (f64.sub (local.get $previous) (local.get $line)) (local.get $step))))
    (local.set $to (f64.floor (f64.div (f64.sub (f64.add (local.get $previous) (local.get $delta)) (local.get $line)) (local.get $step))))
    (if (f64.eq (local.get $from) (local.get $to)) (then (return)))
    (local.set $crossings (i32.trunc_f64_s (f64.min (f64.const 4) (f64.abs (f64.sub (local.get $to) (local.get $from))))))
    (local.set $n (i32.const 1))
    (loop $each
      (local.set $boundary (if (result f64) (f64.gt (local.get $direction) (f64.const 0))
        (then (f64.add (local.get $from) (f64.convert_i32_s (local.get $n))))
        (else (f64.add (f64.sub (local.get $from) (f64.convert_i32_s (local.get $n))) (f64.const 1)))))
      (call $collide (call $pegIndex (f64.neg (local.get $boundary))))
      (local.set $n (i32.add (local.get $n) (i32.const 1))) (br_if $each (i32.le_s (local.get $n) (local.get $crossings)))))

  ;; Unilateral peg contact: pins can lift the pointer, never pull it back.
  (func $pegTorque (result f64)
    (local $motion f64) (local $direction f64) (local $step f64) (local $logical f64) (local $peg i32)
    (local $phase f64) (local $maxDeflection f64) (local $clearance f64) (local $side f64)
    (local $detent f64) (local $target f64) (local $overlap f64) (local $desired f64)
    (local $torque f64) (local $reaction f64) (local $travel f64) (local $approach f64)
    (local $release f64) (local $progress f64) (local $derivative f64) (local $desiredVelocity f64)
    (local.set $motion (call $sign (global.get $w)))
    (if (i32.and (f64.ne (local.get $motion) (f64.const 0)) (i32.lt_s (global.get $contactPeg) (i32.const 0)))
      (then (global.set $lastDirection (local.get $motion))))
    (local.set $direction (if (result f64) (i32.ge_s (global.get $contactPeg) (i32.const 0))
      (then (global.get $contactDirection))
      (else (select (local.get $motion) (global.get $lastDirection) (f64.ne (local.get $motion) (f64.const 0))))))
    (local.set $step (f64.div (global.get $tau) (f64.convert_i32_s (global.get $count))))
    (local.set $logical (call $round (f64.div (f64.sub (global.get $halfPi) (global.get $a)) (local.get $step))))
    (local.set $peg (call $pegIndex (local.get $logical)))
    (local.set $phase (call $signed (f64.sub (f64.add (global.get $a) (f64.mul (local.get $logical) (local.get $step))) (global.get $halfPi))))
    (local.set $maxDeflection (f64.min (f64.const 0.52) (f64.add (f64.const 0.28) (f64.mul (local.get $step) (f64.const 0.28)))))
    ;; At rest, resolve toward the nearest clear detent, including spring
    ;; reaction so a loaded pointer can gently reverse the wheel.
    (if (f64.lt (f64.abs (global.get $w)) (f64.const 0.12)) (then
      (local.set $clearance (f64.min (f64.const 0.06) (f64.mul (local.get $step) (f64.const 0.45))))
      (if (f64.ge (f64.abs (local.get $phase)) (local.get $clearance))
        (then (global.set $contactPeg (i32.const -1)) (return (f64.const 0))))
      (if (i32.ne (global.get $contactPeg) (local.get $peg))
        (then (global.set $contactPeg (local.get $peg)) (call $emitContact (local.get $peg))))
      (local.set $side (select (global.get $lastDirection) (call $sign (local.get $phase))
        (f64.lt (f64.abs (local.get $phase)) (f64.const 1e-5))))
      (local.set $detent (f64.min (f64.mul (local.get $step) (f64.const 0.5)) (f64.add (local.get $clearance) (f64.const 0.01))))
      (local.set $target (if (result f64) (f64.lt (f64.abs (local.get $phase)) (f64.const 1e-5))
        (then (f64.mul (f64.neg (global.get $lastDirection)) (local.get $detent)))
        (else (f64.mul (call $sign (local.get $phase)) (local.get $detent)))))
      (local.set $overlap (f64.sub (f64.const 1) (f64.div (f64.abs (local.get $phase)) (local.get $clearance))))
      (local.set $desired (f64.mul (f64.mul (f64.mul (f64.neg (local.get $side)) (local.get $maxDeflection)) (local.get $overlap)) (local.get $overlap)))
      (local.set $torque (call $clamp (f64.sub (f64.mul (f64.const 125) (f64.sub (local.get $desired) (global.get $p)))
        (f64.mul (f64.const 2) (global.get $v))) (f64.const -35) (f64.const 35)))
      (local.set $reaction (call $clamp (f64.mul (f64.mul (global.get $spring) (global.get $p)) (f64.const 0.018)) (f64.const -0.9) (f64.const 0.9)))
      (global.set $contactTorque (call $clamp (f64.add
        (f64.sub (f64.mul (f64.const 40) (f64.sub (local.get $target) (local.get $phase))) (f64.mul (f64.const 15) (global.get $w)))
        (local.get $reaction)) (f64.const -2.5) (f64.const 2.5)))
      (global.set $lastPeg (local.get $peg)) (return (local.get $torque))))

    (local.set $travel (f64.mul (local.get $phase) (local.get $direction)))
    (local.set $approach (f64.min (f64.const 0.14) (f64.mul (local.get $step) (f64.const 0.62))))
    (local.set $release (f64.min (f64.const 0.06) (f64.mul (local.get $step) (f64.const 0.28))))
    (if (i32.or (f64.le (local.get $travel) (f64.neg (local.get $approach))) (f64.ge (local.get $travel) (local.get $release)))
      (then (global.set $contactPeg (i32.const -1))
        (if (f64.ne (local.get $motion) (f64.const 0)) (then (global.set $lastDirection (local.get $motion))))
        (return (f64.const 0))))
    (if (i32.ne (global.get $contactPeg) (local.get $peg))
      (then (global.set $contactPeg (local.get $peg)) (global.set $contactDirection (local.get $direction)) (call $emitContact (local.get $peg))))
    (local.set $progress (call $clamp (f64.div (f64.add (local.get $travel) (local.get $approach))
      (f64.add (local.get $approach) (local.get $release))) (f64.const 0) (f64.const 1)))
    (local.set $desired (f64.mul (f64.mul (f64.neg (local.get $direction)) (local.get $maxDeflection)) (call $smooth (local.get $progress))))
    (local.set $derivative (f64.mul (f64.mul (f64.const 6) (local.get $progress)) (f64.sub (f64.const 1) (local.get $progress))))
    (local.set $desiredVelocity (f64.div (f64.mul (f64.mul
      (f64.mul (f64.neg (local.get $direction)) (local.get $maxDeflection)) (local.get $derivative)) (f64.abs (global.get $w)))
      (f64.add (local.get $approach) (local.get $release))))
    (local.set $torque (f64.add (f64.mul (f64.const 125) (f64.sub (local.get $desired) (global.get $p)))
      (f64.mul (f64.const 1.8) (f64.sub (local.get $desiredVelocity) (global.get $v)))))
    (if (f64.gt (f64.mul (local.get $torque) (local.get $direction)) (f64.const 0)) (then (local.set $torque (f64.const 0))))
    (local.set $torque (call $clamp (local.get $torque) (f64.const -35) (f64.const 35)))
    (local.set $reaction (f64.max (f64.mul (f64.abs (local.get $torque)) (f64.const 0.028)) (f64.add (global.get $friction) (f64.const 0.06))))
    (global.set $contactTorque (f64.mul (f64.neg (local.get $direction)) (local.get $reaction)))
    (global.set $lastPeg (local.get $peg)) (local.get $torque))

  (func $distance (param $angle f64) (param $pegX f64) (param $pegY f64) (result f64)
    (call $hypot (f64.sub (f64.mul (call $sin (local.get $angle)) (f64.const 0.145)) (local.get $pegX))
      (f64.sub (f64.sub (f64.const 0.955) (f64.mul (call $cos (local.get $angle)) (f64.const 0.145))) (local.get $pegY))))
  ;; Cache the three nearby pin centers once per penetration pass. They do
  ;; not move during the exit scans; the tip is evaluated once per candidate.
  (func $clears (param $angle f64) (result i32)
    (local $x f64) (local $y f64) (local $i i32) (local $address i32)
    (local.set $x (f64.mul (call $sin (local.get $angle)) (f64.const 0.145)))
    (local.set $y (f64.sub (f64.const 0.955) (f64.mul (call $cos (local.get $angle)) (f64.const 0.145))))
    (loop $pins
      (local.set $address (i32.add (i32.const 160) (i32.mul (local.get $i) (i32.const 16))))
      (if (f64.lt (call $hypot (f64.sub (local.get $x) (f64.load (local.get $address)))
        (f64.sub (local.get $y) (f64.load offset=8 (local.get $address)))) (f64.const 0.046)) (then (return (i32.const 0))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br_if $pins (i32.lt_s (local.get $i) (i32.const 3))))
    (i32.const 1))
  (func $penetration (param $dt f64)
    (local $step f64) (local $nearest f64) (local $offset i32) (local $logical f64)
    (local $peg i32) (local $pegAngle f64) (local $address i32) (local $start f64)
    (local $resolved f64) (local $smallest f64) (local $side i32) (local $target f64)
    (local $inside f64) (local $outside f64) (local $found i32) (local $scan i32)
    (local $candidate f64) (local $iteration i32) (local $middle f64) (local $correction f64)
    (local $direction f64) (local $speed f64) (local $phase f64) (local $escape f64)
    (local $distance f64) (local $bit i64) (local $touching i64)
    (local.set $step (f64.div (global.get $tau) (f64.convert_i32_s (global.get $count))))
    (local.set $nearest (call $round (f64.div (f64.sub (global.get $halfPi) (global.get $a)) (local.get $step))))
    (local.set $offset (i32.const -1))
    (loop $cache
      (local.set $pegAngle (f64.add (global.get $a) (f64.mul (f64.add (local.get $nearest) (f64.convert_i32_s (local.get $offset))) (local.get $step))))
      (local.set $address (i32.add (i32.const 160) (i32.mul (i32.add (local.get $offset) (i32.const 1)) (i32.const 16))))
      (f64.store (local.get $address) (f64.mul (call $cos (local.get $pegAngle)) (f64.const 0.83)))
      (f64.store offset=8 (local.get $address) (f64.mul (call $sin (local.get $pegAngle)) (f64.const 0.83)))
      (local.set $offset (i32.add (local.get $offset) (i32.const 1))) (br_if $cache (i32.le_s (local.get $offset) (i32.const 1))))
    (local.set $offset (i32.const -1))
    (loop $pins
      (block $nextPin
        (local.set $logical (f64.add (local.get $nearest) (f64.convert_i32_s (local.get $offset))))
        (local.set $peg (call $pegIndex (local.get $logical)))
        (local.set $pegAngle (f64.add (global.get $a) (f64.mul (local.get $logical) (local.get $step))))
        (local.set $address (i32.add (i32.const 160) (i32.mul (i32.add (local.get $offset) (i32.const 1)) (i32.const 16))))
        (local.set $distance (call $distance (global.get $p) (f64.load (local.get $address)) (f64.load offset=8 (local.get $address))))
        (local.set $bit (i64.shl (i64.const 1) (i64.extend_i32_u (local.get $peg))))
        ;; The approach torque starts well before contact. Only actual tip/pin
        ;; contact produces audio; retain it across the projection's small gap
        ;; so a pin supporting the pointer does not click on every substep.
        (if (i32.and (f64.lt (local.get $distance) (f64.const 0.049))
          (i64.ne (i64.and (global.get $audibleContacts) (local.get $bit)) (i64.const 0)))
          (then (local.set $touching (i64.or (local.get $touching) (local.get $bit)))))
        (br_if $nextPin (f64.ge (local.get $distance) (f64.const 0.046)))
        (if (i64.eqz (i64.and (global.get $audibleContacts) (local.get $bit)))
          (then (call $notify (local.get $peg)
            (call $clamp (f64.div (f64.abs (global.get $w)) (f64.const 17)) (f64.const 0.06) (f64.const 1)))))
        (local.set $touching (i64.or (local.get $touching) (local.get $bit)))
        (local.set $start (global.get $p)) (local.set $resolved (f64.const nan)) (local.set $smallest (f64.const inf))
        (local.set $side (i32.const 0))
        (loop $sides
          (local.set $target (select (f64.const -1) (f64.const 1) (i32.eqz (local.get $side))))
          (local.set $inside (local.get $start)) (local.set $outside (local.get $target))
          (local.set $found (i32.const 0)) (local.set $scan (i32.const 1))
          (block $scanned (loop $scanLoop
            (local.set $candidate (f64.add (local.get $start)
              (f64.div (f64.mul (f64.sub (local.get $target) (local.get $start)) (f64.convert_i32_s (local.get $scan))) (f64.const 32))))
            (if (call $clears (local.get $candidate))
              (then (local.set $outside (local.get $candidate)) (local.set $found (i32.const 1)) (br $scanned)))
            (local.set $inside (local.get $candidate))
            (local.set $scan (i32.add (local.get $scan) (i32.const 1))) (br_if $scanLoop (i32.le_s (local.get $scan) (i32.const 32)))))
          (if (local.get $found) (then
            (local.set $iteration (i32.const 0))
            (loop $bisect
              (local.set $middle (f64.mul (f64.add (local.get $inside) (local.get $outside)) (f64.const 0.5)))
              (if (call $clears (local.get $middle)) (then (local.set $outside (local.get $middle))) (else (local.set $inside (local.get $middle))))
              (local.set $iteration (i32.add (local.get $iteration) (i32.const 1))) (br_if $bisect (i32.lt_s (local.get $iteration) (i32.const 12))))
            (local.set $correction (f64.abs (f64.sub (local.get $outside) (local.get $start))))
            (if (f64.lt (local.get $correction) (local.get $smallest))
              (then (local.set $smallest (local.get $correction)) (local.set $resolved (local.get $outside))))))
          (local.set $side (i32.add (local.get $side) (i32.const 1))) (br_if $sides (i32.lt_s (local.get $side) (i32.const 2))))
        (if (f64.ne (local.get $resolved) (local.get $resolved)) (then (local.set $resolved (f64.neg (global.get $lastDirection)))))
        (local.set $correction (f64.sub (local.get $resolved) (global.get $p)))
        (local.set $direction (call $sign (local.get $correction)))
        (if (f64.eq (local.get $direction) (f64.const 0)) (then (local.set $direction (f64.const 1))))
        (global.set $p (call $clamp (f64.add (local.get $resolved) (f64.mul (local.get $direction) (f64.const 0.001))) (f64.const -1) (f64.const 1)))
        (local.set $speed (f64.abs (global.get $w)))
        ;; Low-speed projection dissipates velocity; it must not inject energy.
        (if (f64.lt (local.get $speed) (f64.const 0.5)) (then
          (global.set $v (f64.mul (global.get $v) (select (f64.const 0.12) (f64.const 0.62) (f64.lt (local.get $speed) (f64.const 0.12)))))
          (if (f64.lt (local.get $speed) (f64.const 0.12)) (then
            (local.set $phase (call $signed (f64.sub (local.get $pegAngle) (global.get $halfPi))))
            (local.set $escape (select (call $sign (local.get $phase)) (local.get $direction) (f64.gt (f64.abs (local.get $phase)) (f64.mul (local.get $step) (f64.const 0.5)))))
            (global.set $contactTorque (f64.mul (local.get $escape) (f64.add (global.get $friction) (f64.const 0.08)))))))
          (else (global.set $v (call $clamp (f64.add (global.get $v) (f64.mul (f64.div (local.get $correction) (local.get $dt)) (f64.const 0.035))) (f64.const -9) (f64.const 9)))))
        (if (i32.ne (global.get $contactPeg) (local.get $peg)) (then (global.set $contactPeg (local.get $peg)) (call $emitContact (local.get $peg)))))
      (local.set $offset (i32.add (local.get $offset) (i32.const 1))) (br_if $pins (i32.le_s (local.get $offset) (i32.const 1))))
    (global.set $audibleContacts (local.get $touching)))

  (func $integrate (param $dt f64)
    (local $applied f64) (local $omega f64) (local $resistance f64) (local $contact f64)
    (local $previous f64) (local $pointerTorque f64) (local $stopped i32)
    (global.set $time (f64.add (global.get $time) (local.get $dt)))
    (if (f64.gt (global.get $launchRemaining) (f64.const 0)) (then
      (local.set $applied (f64.min (local.get $dt) (global.get $launchRemaining)))
      (global.set $w (f64.add (global.get $w) (f64.div (f64.mul (global.get $launchTorque) (local.get $applied)) (global.get $inertia))))
      (global.set $launchRemaining (f64.sub (global.get $launchRemaining) (local.get $applied)))))
    (local.set $omega (global.get $w))
    (local.set $resistance (f64.add (f64.add
      (f64.sub (f64.mul (f64.mul (f64.neg (global.get $linear)) (global.get $dragScale)) (local.get $omega))
        (f64.mul (f64.mul (global.get $quadratic) (local.get $omega)) (f64.abs (local.get $omega))))
      (call $brakeTorque (local.get $omega) (f64.mul (global.get $brake) (global.get $brakeScale)))) (global.get $contactTorque)))
    (local.set $contact (global.get $contactTorque)) (global.set $contactTorque (f64.const 0))
    (if (f64.gt (f64.abs (local.get $omega)) (f64.const 0.0001))
      (then (local.set $resistance (f64.sub (local.get $resistance) (f64.mul (call $sign (local.get $omega)) (global.get $friction)))))
      (else (if (f64.le (f64.abs (local.get $resistance)) (global.get $friction))
        (then (local.set $resistance (f64.const 0)))
        (else (local.set $resistance (f64.sub (local.get $resistance) (f64.mul (call $sign (local.get $resistance)) (global.get $friction))))))))
    (local.set $previous (global.get $a))
    (global.set $w (f64.add (global.get $w) (f64.mul (f64.div (local.get $resistance) (global.get $inertia)) (local.get $dt))))
    (if (i32.and (i32.and (f64.ne (local.get $omega) (f64.const 0)) (f64.ne (call $sign (local.get $omega)) (call $sign (global.get $w))))
      (f64.le (f64.abs (local.get $contact)) (global.get $friction))) (then (global.set $w (f64.const 0))))
    (global.set $a (call $wrap (f64.add (global.get $a) (f64.mul (global.get $w) (local.get $dt)))))
    (call $crossings (local.get $previous) (global.get $a))
    (local.set $contact (call $pegTorque))
    (local.set $pointerTorque (f64.add
      (f64.sub (f64.mul (f64.neg (global.get $spring)) (global.get $p)) (f64.mul (global.get $damping) (global.get $v))) (local.get $contact)))
    (global.set $v (f64.add (global.get $v) (f64.mul (f64.div (local.get $pointerTorque) (global.get $pointerInertia)) (local.get $dt))))
    (global.set $p (call $clamp (f64.add (global.get $p) (f64.mul (global.get $v) (local.get $dt))) (f64.const -1) (f64.const 1)))
    (call $penetration (local.get $dt))
    (global.set $strength (f64.mul (global.get $strength) (global.get $decay)))
    (local.set $stopped (i32.and (i32.and
      (i32.and (f64.lt (f64.abs (global.get $w)) (f64.const 0.025)) (f64.lt (f64.abs (global.get $v)) (f64.const 0.06)))
      (i32.and (f64.lt (f64.abs (global.get $p)) (f64.const 0.012)) (i32.lt_s (global.get $contactPeg) (i32.const 0))))
      (f64.le (global.get $launchRemaining) (f64.const 0))))
    (global.set $stable (select (f64.add (global.get $stable) (local.get $dt)) (f64.const 0) (local.get $stopped)))
    (if (f64.ge (global.get $stable) (f64.const 0.35)) (then (global.set $w (f64.const 0)))))

  ;; Shared integrator: globals stay live across ticks in a batch.
  (func $tick (param $dt f64)
    (local $launchDelta f64) (local $speed f64) (local $maxTravel f64)
    (local $springSteps f64) (local $dampingSteps f64) (local $travelSteps f64)
    (local $subdivisions i32) (local $i i32) (local $subDt f64)
    (call $writeState (i32.const 224))
    (local.set $launchDelta (f64.div (f64.mul (global.get $launchTorque) (f64.min (local.get $dt) (global.get $launchRemaining))) (global.get $inertia)))
    (local.set $speed (f64.add (f64.abs (global.get $w)) (f64.abs (local.get $launchDelta))))
    (local.set $maxTravel (f64.min (f64.const 0.025) (f64.div (f64.div (global.get $tau) (f64.convert_i32_s (global.get $count))) (f64.const 8))))
    (local.set $springSteps (f64.div (f64.mul (local.get $dt) (f64.sqrt (f64.div (f64.add (global.get $spring) (f64.const 125)) (global.get $pointerInertia)))) (f64.const 0.5)))
    (local.set $dampingSteps (f64.div (f64.mul (local.get $dt) (f64.add (global.get $damping) (f64.const 2))) (global.get $pointerInertia)))
    (local.set $travelSteps (f64.div (f64.mul (local.get $speed) (local.get $dt)) (local.get $maxTravel)))
    (local.set $subdivisions (i32.trunc_f64_s (call $clamp (f64.ceil (f64.max (f64.max (local.get $travelSteps) (local.get $springSteps)) (local.get $dampingSteps))) (f64.const 1) (f64.const 32))))
    (local.set $subDt (f64.div (local.get $dt) (f64.convert_i32_s (local.get $subdivisions))))
    ;; Every substep has the same dt; calculate impact decay only once.
    (global.set $decay (call $exp (f64.mul (f64.neg (local.get $subDt)) (f64.const 9))))
    (loop $substeps
      (call $integrate (local.get $subDt))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br_if $substeps (i32.lt_s (local.get $i) (local.get $subdivisions))))
  )

  (func (export "step") (param $dt f64)
    (call $read) (global.set $events (i32.const 0))
    (call $tick (local.get $dt)) (call $publish))

  ;; Animation: exactly the requested ticks, retaining the final two states.
  ;; Limit matches FixedStepLoop's catch-up cap and bounds event memory.
  (func (export "advance") (param $ticks i32) (local $i i32)
    (if (i32.gt_u (local.get $ticks) (i32.const 30)) (then unreachable))
    (call $read) (global.set $events (i32.const 0))
    (block $done (loop $ticksLoop
      (br_if $done (i32.ge_u (local.get $i) (local.get $ticks)))
      (call $tick (global.get $fixedDt))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $ticksLoop)))
    (call $publish))

  ;; Diagnostics: stop at the first settled outer tick or the caller's cap.
  ;; No event accumulation, so arbitrarily long runs cannot overflow audio.
  ;; Duration is for this call; result is -1 if the cap was reached unsettled.
  (func (export "run_until_settled") (param $maxTicks i32) (result i32) (local $ticks i32)
    (if (i32.lt_s (local.get $maxTicks) (i32.const 0)) (then unreachable))
    (call $read) (global.set $events (i32.const 0)) (global.set $captureEvents (i32.const 0))
    (block $done (loop $run
      (br_if $done (i32.or (i32.ge_u (local.get $ticks) (local.get $maxTicks))
        (f64.ge (global.get $stable) (f64.const 0.35))))
      (call $tick (global.get $fixedDt))
      (local.set $ticks (i32.add (local.get $ticks) (i32.const 1))) (br $run)))
    (global.set $captureEvents (i32.const 1))
    (f64.store (i32.const 288) (f64.mul (f64.convert_i32_s (local.get $ticks)) (global.get $fixedDt)))
    (f64.store (i32.const 296) (if (result f64) (f64.ge (global.get $stable) (f64.const 0.35))
      (then (f64.convert_i32_s (i32.rem_u (i32.trunc_f64_u
        (f64.floor (f64.div (call $wrap (f64.sub (global.get $halfPi) (global.get $a)))
          (f64.div (global.get $tau) (f64.convert_i32_s (global.get $count)))))) (global.get $count))))
      (else (f64.const -1))))
    (call $publish) (local.get $ticks))
)
